version = 0.1
[default.deploy.parameters]
stack_name = "liqi-challenge2-stack"
resolve_s3 = true
s3_prefix = "liqi-challenge2-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
